{{- include "ffc-helm-library.container-config-map" (list . "ffc-sfi-agreement-viewer.config-map") -}}
{{- define "ffc-sfi-agreement-viewer.config-map" -}}
data:
  NODE_ENV: {{ quote .Values.environment }}
  PORT: {{ quote .Values.container.port }}
  APPINSIGHTS_CLOUDROLE: {{ quote .Values.name }}
  MESSAGE_QUEUE_HOST: {{ quote .Values.container.messageQueueHost }}
  ELIGIBILITY_TOPIC_ADDRESS: {{ quote .Values.container.eligibilityTopicAddress }}
  ELIGIBILITY_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.eligibilitySubscriptionAddress }}
  STANDARDS_TOPIC_ADDRESS: {{ quote .Values.container.standardsTopicAddress }}
  STANDARDS_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.standardsSubscriptionAddress }}
  VALIDATE_TOPIC_ADDRESS: {{ quote .Values.container.validateTopicAddress }}
  VALIDATE_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.validateSubscriptionAddress }}
  CALCULATE_TOPIC_ADDRESS: {{ quote .Values.container.calculateTopicAddress }}
  CALCULATE_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.calculateSubscriptionAddress }}
  SUBMIT_TOPIC_ADDRESS: {{ quote .Values.container.submitTopicAddress }}
  SUBMIT_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.submitSubscriptionAddress }}
  WITHDRAW_TOPIC_ADDRESS: {{ quote .Values.container.withdrawTopicAddress }}
  WITHDRAW_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.withdrawSubscriptionAddress }}
  PAYMENT_API_TOPIC_ADDRESS: {{ quote .Values.container.paymentApiTopicAddress }}
  PAYMENT_API_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.paymentApiSubscriptionAddress }}
  PAYMENT_CALCULATOR_TOPIC_ADDRESS: {{ quote .Values.container.paymentCalculatorTopicAddress }}
  PAYMENT_CALCULATOR_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.paymentCalculatorSubscriptionAddress }}
  WITHDRAW_API_TOPIC_ADDRESS: {{ quote .Values.container.withdrawApiTopicAddress }}
  WITHDRAW_API_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.withdrawApiSubscriptionAddress }}
  WITHDRAW_CALCULATOR_TOPIC_ADDRESS: {{ quote .Values.container.withdrawCalculatorTopicAddress }}
  WITHDRAW_CALCULATOR_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.withdrawCalculatorSubscriptionAddress }}
  WITHDRAW_VIEWER_TOPIC_ADDRESS: {{ quote .Values.container.withdrawViewerTopicAddress }}
  WITHDRAW_VIEWER_SUBSCRIPTION_ADDRESS: {{ quote .Values.container.withdrawViewerSubscriptionAddress }}
{{- end -}}
