{{- include "ffc-helm-library.container-secret" (list . "ffc-sfi-agreement-viewer.container-secret") -}}
{{- define "ffc-sfi-agreement-viewer.container-secret" -}}
stringData:
  {{- if .Values.appInsights.key }}
  APPINSIGHTS_INSTRUMENTATIONKEY: {{ quote .Values.appInsights.key }}
  {{- end }}
{{- end -}}
